name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'

jobs:

  build:
    strategy:
      matrix:
        rust_version: ["1.82", "latest", "beta", "nightly"] # 1.82: oldest supported version
      fail-fast: false

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set rust version in devcontainer
      run: ./scripts/set-rust-version.sh ${{ matrix.rust_version }}

    - name: Build and test
      uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3.1900000449
      with:
        runCmd: ./scripts/ci.sh
