name: Code coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'

jobs:

  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set rust version in devcontainer
      run: ./scripts/set-rust-version.sh nightly

    - name: Code coverage
      uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
      with:
        runCmd: ./scripts/coverage.sh
