name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and test
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-devcontainer
        cacheFrom: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-devcontainer
        push: always  
